import React from 'react';
import { useBusinessStore } from '../../store/useBusinessStore';
import { Shield, Zap, Globe, Cpu } from 'lucide-react';

const StatBox = ({ icon: Icon, title, value, color }) => (
  <div className="bg-zinc-900/40 border border-white/5 p-6 rounded-3xl flex items-center gap-4">
    <div className={`w-12 h-12 rounded-2xl flex items-center justify-center ${color} bg-opacity-10`}>
      <Icon className={color.replace('bg-', 'text-')} size={24} />
    </div>
    <div>
      <p className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest">{title}</p>
      <p className="text-xl font-bold text-white">{value}</p>
    </div>
  </div>
);

const HomeView = () => {
  const { metrics } = useBusinessStore();

  return (
    <div className="space-y-12 animate-in fade-in duration-1000">
      {/* Hero Section */}
      <div className="relative h-[400px] rounded-[3rem] overflow-hidden flex flex-col justify-center px-12 border border-white/5 shadow-2xl">
        <div className="absolute inset-0 bg-gradient-to-r from-indigo-600/20 to-transparent z-10"></div>
        <div className="absolute inset-0 bg-[#09090b] z-0"></div>
        <div className="absolute -top-24 -right-24 w-96 h-96 bg-indigo-500/10 blur-[120px] rounded-full"></div>
        
        <div className="relative z-20 max-w-2xl space-y-6">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-[10px] font-bold text-indigo-400 uppercase tracking-tighter">
            System Status: Operational
          </div>
          <h1 className="text-6xl font-bold text-white tracking-tighter leading-none">
            Sifu <span className="text-indigo-500">5.2</span><br/>NHITL Factory
          </h1>
          <p className="text-zinc-400 text-lg leading-relaxed">
            The next generation of Autonomous Solution Architecture. Converting voice requirements into production-ready CCaaS infrastructure in real-time.
          </p>
          <div className="flex gap-4 pt-4">
            <div className="px-6 py-3 rounded-2xl bg-white text-black font-bold text-sm cursor-pointer hover:bg-zinc-200 transition-colors">
              Launch Simulation
            </div>
            <div className="px-6 py-3 rounded-2xl bg-white/5 border border-white/10 text-white font-bold text-sm cursor-pointer hover:bg-white/10 transition-colors">
              View Architecture
            </div>
          </div>
        </div>
      </div>

      {/* Quick Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatBox icon={Shield} title="Security Compliance" value="Enterprise Gold" color="bg-emerald-500" />
        <StatBox icon={Zap} title="Orchestration Latency" value="~140ms" color="bg-amber-500" />
        <StatBox icon={Globe} title="Deployment Target" value="GCP Cloud Run" color="bg-blue-500" />
        <StatBox icon={Cpu} title="Active Agents" value="11 Core Workers" color="bg-purple-500" />
      </div>

      {/* Strategy Teaser */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="p-8 rounded-[2.5rem] bg-zinc-900/20 border border-white/5 backdrop-blur-3xl space-y-4">
          <h3 className="text-xl font-bold text-white">The Power of Zero-Trust Code</h3>
          <p className="text-zinc-500 text-sm leading-relaxed">
            Our ZTA Validator ensures that every line of code generated by our Lead Coder Agent passes a physical build test and a GRC audit before hitting production. This eliminates human error and guarantees 100% reliability in mission-critical environments.
          </p>
        </div>
        <div className="p-8 rounded-[2.5rem] bg-zinc-900/20 border border-white/5 backdrop-blur-3xl space-y-4">
          <h3 className="text-xl font-bold text-white">Hyper-Personalization at Scale</h3>
          <p className="text-zinc-500 text-sm leading-relaxed">
            By leveraging Gemini 3.1 Pro's reasoning capabilities, the factory doesn't just build apps; it designs custom CCaaS topologies that adapt to the specific needs of Genesys, Salesforce, and Amazon Connect ecosystems.
          </p>
        </div>
      </div>
    </div>
  );
};

export default HomeView;
